/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bloodbank;
import javax.swing.table.*;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author anand
 */
public class updatestock extends javax.swing.JFrame {

    /** Creates new form updatestock */
    public updatestock() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","Sharath@1220");
            DefaultTableModel model=(DefaultTableModel) Table.getModel();
            Table.setModel(model);
            String sql="select * from stock";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            String b,u;
            while(rs.next()){
                b=rs.getString(1);
                u=rs.getString(2);
                
                model.addRow(new Object[]{b,u});
            }
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ddlblood = new javax.swing.JComboBox<>();
        btnincrease = new javax.swing.JButton();
        btndecrease = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtunit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setLocation(new java.awt.Point(280, 80));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Update Blood Stock");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 11, 415, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 65, 671, 10));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOOD GROUP", "UNITS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 141, 649, 279));

        jLabel2.setText("Select Blood Group");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 84, 120, -1));

        ddlblood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        getContentPane().add(ddlblood, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 116, -1));

        btnincrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inc.png"))); // NOI18N
        btnincrease.setText("Increase");
        btnincrease.setFocusable(false);
        btnincrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnincreaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnincrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 458, -1, -1));

        btndecrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dec.png"))); // NOI18N
        btndecrease.setText("Decrease");
        btndecrease.setFocusable(false);
        btndecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndecreaseActionPerformed(evt);
            }
        });
        getContentPane().add(btndecrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 458, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 117, 670, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 438, 680, -1));
        getContentPane().add(txtunit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 134, -1));

        jLabel3.setText("Units :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 84, 50, -1));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exit application.png"))); // NOI18N
        btnclose.setText("Close");
        btnclose.setFocusable(false);
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 458, -1, -1));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-close-window-30.png"))); // NOI18N
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 0, 24, 25));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CLOSE APPLICATION","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnincreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnincreaseActionPerformed
       String blood=ddlblood.getSelectedItem().toString();
       String u=txtunit.getText();
       if(!u.matches("\\d+")||u.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter unit");
            return;
        }
        int unit=Integer.parseInt(u);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","Sharath@1220");
            String q="update stock set units=units+? where blood_group=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setInt(1,unit);
            ps.setString(2,blood);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,blood+"  increased by "+unit+" units");
            new updatestock().setVisible(true);
            dispose();
       }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btnincreaseActionPerformed

    private void btndecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndecreaseActionPerformed
        String blood=ddlblood.getSelectedItem().toString();
       String u=txtunit.getText();
       if(!u.matches("\\d+")||u.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter unit");
            return;
        }
        int unit=Integer.parseInt(u);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbank","root","Sharath@1220");
            String q="update stock set units=units-? where blood_group=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setInt(1,unit);
            ps.setString(2,blood);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,blood+"  Decreased by "+unit+" units");
            new updatestock().setVisible(true);
            dispose();
       }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_btndecreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatestock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatestock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndecrease;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnincrease;
    private javax.swing.JComboBox<String> ddlblood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtunit;
    // End of variables declaration//GEN-END:variables

}
